#!/bin/bash

if [ -e R_Programming_Week2.pdf ]
then
    echo 'WARNING: Target file exists. Will replace with new file.'
    rm -rf R_Programming_Week2.pdf

fi

#arr=(/home/thomas/Coursera/R_Programming/Week2/*pdf(Nom))
#arr=(./*pdf (NOm) )
arr=(*pdf)
#sorthelper=();
#for file in "${arr[@]}"; do
    # We need something that can easily be sorted.
    # Here, we use "<date><filename>".
    # Note that this works with any special characters in filenames
#    sorthelper+=("$(stat --printf "%Y    %n" -- "$file")"); # Linux only
#done;

#for file in "${sorthelper[@]}"; do
#    echo "$file"
#done

#sorted=();
#while read -d $'\0' elem; do
    # this strips away the first 14 characters (<date>) 
#    sorted+=("${elem:14}");
#done < <(printf '%s\0' "${sorthelper[@]}" | sort -z)
    
for file in "${arr[@]}"; do
    echo "$file";
done;
#for ((i=0; i<${#arr[@]}; i++)); do
#    echo "${arr[$i]}"
#done

pdftk ${arr[*]} cat output R_Programming_Week2.pdf
